[metadata]
name = PyAltium365
version = 0.1.0
description = an library that can interface with altium 365
author = Dylan Gybels
author_email = GybelsDylan@gmail.com
license = MIT
license_file = LICENSE
platforms = unix, linux, osx, cygwin, win32
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
include_package_data = True
packages =
    PyAltium365
install_requires =
    requests>=2
    pydantic>=1.8.2
python_requires = >=3.7
package_dir =
    =src
zip_safe = no

[options.extras_require]
testing =
    pytest>=6.0
    pytest-cov>=2.0
    mypy>=0.910
    flake8>=5.0.0
    tox>=4.2

[options.package_data]
PyAltium365 = py.typed

[flake8]
max-line-length = 160
count = True
ignore =
indent-size = 4
statistics = True
doctests = True